#!/bin/bash
echo -e "\n*******  Enabling Security for Riak  *******"
riak stop
mv /etc/riak/riak.conf /etc/riak/riak.orig
mv /etc/riak/riak.conf.mod /etc/riak/riak.conf
genCert.sh
updateConf.sh
rm -rf /var/lib/riak/bitcask/ 
rm -rf /var/lib/riak/ring/
riak start
riak-admin security enable 
riak-admin security add-user tom password=tom 
riak-admin security grant riak_kv.get,riak_kv.put,riak_kv.delete,riak_kv.index,riak_kv.list_keys,riak_kv.list_buckets,riak_core.get_bucket,riak_core.set_bucket,riak_core.get_bucket_type,riak_core.set_bucket_type,riak_kv.mapreduce on any to all 
riak-admin security add-source all 0.0.0.0/0 password
riak-admin bucket-type create animals
riak-admin bucket-type activate animals
riak-admin bucket-type list
riak-admin bucket-type status animals
riak ping
echo -e "\n*******  Finished Enabling Security for Riak  *******"